name: Pages

on:
  push:
    branches:
      - main # default branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # If your repository depends on submodule, please see: https://github.com/actions/checkout
          submodules: recursive
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          # Examples: 20, 18.19, >=16.20.2, lts/Iron, lts/Hydrogen, *, latest, current, node
          # Ref: https://github.com/actions/setup-node#supported-version-syntax
          node-version: "20"
      - name: Cache NPM dependencies
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache
      - name: Install Dependencies
        run: npm install
      - name: Install Gulp CLI globally
        run: npm install --global gulp-cli
      - name: Build
        run: npm run build
      - name: Run Gulp to compress resources
        run: gulp
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
  push_to_gitlab:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code for GitLab push
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Push to GitLab
        run: |
          git remote add gitlab https://wit-l:${{ secrets.GITLAB_TOKEN }}@gitlab.com/wit-l/wit-l.gitlab.io.git
          git pull gitlab main --rebase=true || true
          git diff
          git push -u gitlab main
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
  push_to_jihulab:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code for JihuLab push
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Push to JihuLab
        run: |
          git remote add jihulab https://wit-lu:${{ secrets.JIHULAB_TOKEN }}@jihulab.com/wit-lu/wit-lu.jihulab.io.git
          git pull jihulab main --rebase=true || true
          git diff
          git push -u jihulab main
        env:
          JIHULAB_TOKEN: ${{ secrets.JIHULAB_TOKEN }}
